### ISSUE TITLE
About 2d bboxes and centers at image boundaries.

### ISSUE THREAD

**Issue by xu19971109** [yichen928/SparseFusion#30]
I reivew `def project_to_image` in combine_view_info.py 
I find you first project `center3d_lidar` to `center3d_cam` to `center2d`.
Then  filter the `center2d` by depth and img boundaries. At last, the function returns a mask to keep 2d bboxes indices.
At this process, `center2d` will be drop when center out of the img, but `center2d` not in img doesn't meam there is no 2d bbox in img. Like the pic
I also find you supervise the `ceter2d` in the loss.  Is dropping the boxes which center2d out of the image boundary to remove 2d center supervision or is it a bug?

white is from you， green is from coco.
<img width="1128" alt="image" src="https://github.com/yichen928/SparseFusion/assets/50237122/6eed21bd-b5c7-45b7-a7c0-9c057c0bb3ab">

**Comment by yichen928** [comment]
Thanks for your interest! 

We think it would be hard for the network to identify the object based on a very small region inside the image. Therefore, we filter the 2D objects by the 2D center coordinates. This is also convenient for implementation since we need to supervised the 2D center position. We did not try to remove the center supervision for the cases that centers are out of the boundary. You can make a try if you are interested, but I think there would not be a large effect.
